version: '2'
services:
  db:
    image: mariadb:10.2
    restart: always
    environment:
      - MYSQL_DATABASE=mozillians
      - MYSQL_USER=mozillians
      - MYSQL_PASSWORD=mozillians
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mariadb_volume:/var/lib/mysql
      - ./docker/files/mariadb.cnf:/etc/mysql/conf.d/my.cnf
  es:
    image: elasticsearch:2.4.5
  memcached:
    image: memcached
  broker:
    image: redis:3
  web:
    build:
      context: .
      dockerfile: docker/dev
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - .:/code
    links:
      - db
      - es
      - memcached
      - broker
  celery:
    build:
      context: .
      dockerfile: docker/dev
    volumes:
      - .:/code
    links:
      - db
      - es
      - broker
      - memcached
    command: ./bin/run-celery.sh
    environment:
      - C_FORCE_ROOT=true
  flower:
    build:
      context: .
      dockerfile: docker/dev
    volumes:
      - .:/code
    links:
      - db
      - broker
    ports:
      - "5555:5555"
    command: flower -A mozillians --address=0.0.0.0 --port=5555
volumes:
  mariadb_volume:

