{{ if eq .Values.env "staging" }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: avatar-sc
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zones: us-west-2a, us-west-2b
reclaimPolicy: Retain
mountOptions:
  - debug

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: avatar-pvc
  namespace: {{ .Values.namespace }}
  labels:
    name: avatar-pvc
spec:
  storageClassName: avatar-sc
  resources:
    requests:
      storage: 6Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: avatar-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: avatar-nginx
        app: avatar-nginx
    spec:
      containers:
        - image: nginx
          name: avatar-nginx
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: avatar-pv
      volumes:
        - name: avatar-pv
          persistentVolumeClaim:
            claimName: avatar-pvc

---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    name: dino-park-avatar
  name: dino-park-avatar
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: avatar-nginx

{{ end }}
