---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

{{ if eq .Values.env "dev" -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-mysql-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-redis-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-memcached-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}-memcached
  ports:
    - protocol: TCP
      port: 11211
      targetPort: 11211

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-es-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.name }}-es
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
{{ end -}}
