---
apiVersion: v1
kind: Service
metadata:
  name: dino-park-mozillians-service
  namespace: dino-park
spec:
  selector:
    app: dino-park-mozillians
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: dino-park-mysql-service
  namespace: dino-park
spec:
  selector:
    app: dino-park-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: dino-park-redis-service
  namespace: dino-park
spec:
  selector:
    app: dino-park-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: dino-park-memcached-service
  namespace: dino-park
spec:
  selector:
    app: dino-park-memcached
  ports:
    - protocol: TCP
      port: 11211
      targetPort: 11211

---
apiVersion: v1
kind: Service
metadata:
  name: dino-park-es-service
  namespace: dino-park
spec:
  selector:
    app: dino-park-es
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
